<br /><br />
<div id="view-content">
  <p>View script for controller <b>Piece</b> and script/action name <b>index</b></p>
</div>

<p>
  <a href="<?php echo $this->url(array('controller' => 'piece', 'action' => 'add'), 'default', true)?>">Add a piece</a>
</p>

Pieces: 
<br />
<?php
$pieces = $this->inbox;
?>
<table id="pieces">

<?php 
$alt = 0;
foreach ($pieces as $piece): ?>
  
  <?php if($alt % 2 == 0){?>
  <tr class="alt">
  <?php } else { ?> <tr> <?php } ?>
    
    <td><?php echo $this->escape($piece->week) ?></td>
  <?php if ($piece->devUrl != NULL) { ?>
    <td>
      <a href="<?php echo $this->escape($piece->devUrl) ?>" target="_blank"><?php echo $this->escape($piece->name) ?></a>
    </td><?php
  }
  else {?>
    <td>
      <?php echo $this->escape($piece->name); ?>
    </td>
    <?php }
  
  if ($piece->gitUrl != NULL) {
    ?>
    <td>
      <a href="<?php echo $this->escape($piece->gitUrl) ?>" target="_blank">Git</a>
    </td>
  <?php }
  else { ?><td>-</td><?php }
  if ($piece->liveUrl != NULL) {
    ?>
    <td>
      <a href="<?php echo $this->escape($piece->liveUrl) ?> " target="_blank">Live</a>
    </td>
    <?php }
    else { ?><td>-</td><?php }
    if ($piece->designUrl != NULL) {
      ?>
    <td>
      <a href="<?php echo $this->escape($piece->designUrl) ?> " target="_blank">Design</a>
    </td>
    <?php }
    else { ?><td>-</td><?php }
    if ($piece->typeName != NULL) { ?> 
    <td>
      <?php echo $this->escape($piece->typeName) ?>
    </td>
  <?php }
  else { ?><td>-</td><?php }
  if ($piece->comment != NULL) { ?> 
    <td>
      <?php echo $this->escape($piece->comment) ?>
    </td>
  <?php }
  else { ?><td>-</td><?php }
  ?>
    </tr>
<?php 
$alt++;
endforeach ?>
</table>
