<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Mei</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  </head>
  <body>

    <div id="header" style="background-color: #EEEEEE; height: 30px;">
      <div id="header-logo" style="float: left">
        <b>Mei</b>
      </div>
      <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(['controller' => 'piece'], 'default', true) ?>">Pieces</a>
      </div>
    </div>
    <?php 
//    $t = new Application_Model_DbTable_Piece();
//    echo get_class($t);
    ?>

    <?php echo $this->layout()->content; ?>
    <footer style="background-color: #EEEEEE; height: 30px;">Mei</footer>
  </body>
</html>